name: Daily product scrape

on:
  schedule:
    - cron: '30 1 * * *'   # 01:30 UTC = 08:30 GMT+7 (Jakarta)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      ISLANDSUN_USERNAME: ${{ secrets.ISLANDSUN_USERNAME }}
      ISLANDSUN_PASSWORD: ${{ secrets.ISLANDSUN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests; fi

      - name: Run scraper
        run: python product_scraper.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add products.json last_updated.txt || true
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update products.json and last_updated.txt: $(cat last_updated.txt)"
            git push
          fi